### ISSUE TITLE
Definición del alcance del proyecto

### ISSUE THREAD

**Issue by nicsanmen** [TFG-nicsanmen-rubsuadav/Planificacion#1]
Como primer paso vamos a definir lo que es la declaración del alcance del proyecto que vamos a desarrollar. Haremos uso de [este documento](https://es.overleaf.com/project/65108d0becf2232d455ded62) de Overleaf.

**Comment by rubsuadav** [comment]
Propongo este alcance del proyecto:
Se desarrollará una solución software que permita a nuestros clientes gestionar un bar o restaurante de manera eficiente, ofreciendo la posibilidad de reserva de mesas a través de una plataforma online. La aplicación dividirá los horarios de apertura en intervalos de reserva, permitiendo a los usuarios seleccionar un horario específico y el tipo de experiencia que desean, ya sea cena formal, cócteles informales u otros eventos especiales. Además, la aplicación también proporcionará herramientas para el administrador, permitiéndole llevar un control detallado del inventario de bebidas y alimentos, así como la gestión de eventos especiales y promociones.
Además también existirá la posibilidad de poder realizar el pago de manera online a través de la aplicación.
