### ISSUE TITLE
Definición de los requisitos del proyecto

### ISSUE THREAD

**Issue by nicsanmen** [TFG-nicsanmen-rubsuadav/Planificacion#3]
Definiremos los requisitos para este proyecto dividiéndolos inicialmente en requisitos funcionales y no funcionales.

**Comment by rubsuadav** [comment]
Propongo estos requisitos iniciales:
- **Como** cliente **quiero** registrarme en la aplicación  **para** poder reservar una mesa el día que yo quiera ir al establecimiento
-  **Como** cliente **quiero** registrarme en la aplicación  **para** poder escribir una valoración del plato
- **Como** administrador** quiero** registrarme en la aplicación  **para** poder gestionar el inventario de alimentación
-  **Como** administrador**quiero** registrarme en la aplicación  **para** poder gestionar los eventos espaciales del establecimiento
- **Como** cliente **quiero** registrarme en la aplicación  **para** realizar el pago de la consumición del establecimiento de manera online desde la aplicación
- **Como** cliente **quiero** registrarme en la aplicación  **para** poder ver las valoraciones de los platos con sus respectivos comentario
-  **Como** cliente **quiero** ver la carta del establecimiento **para** elegir lo que voy a consumir en el establecimiento
- **Como** cliente **quiero** iniciar sesión en la aplicación  **para** estar logado como cliente una vez tenga mi cuenta creada
