### ISSUE TITLE
Definir nombre del proyecto

### ISSUE THREAD

**Issue by nicsanmen** [TFG-nicsanmen-rubsuadav/Planificacion#4]
Uno de los primeros pasos es decidir un nombre para el proyecto, a ser posible que esté relacionado con la temática.

**Comment by rubsuadav** [comment]
Los nombres que he pensado son:
EatSpot
Bar&RestoFinder
Gastronomix

Se basan en el tema de "donde quieras, cuando quieras"

**Comment by rubsuadav** [comment]
Se ha decidido al final el nombre de GOODMENU
