### ISSUE TITLE
Analisis de tecnologias

### ISSUE THREAD

**Issue by rubsuadav** [TFG-nicsanmen-rubsuadav/Planificacion#6]
Se debe de realizar un análisis de las tecnologías que usaremos durante la realización del TFG

**Comment by rubsuadav** [comment]
Se ha realizado un estudio exhaustivo del análisis de las posibles tecnologías analizando pros y contras de cada una de ellas eligiendo el stack ideal para nosotros, a la espera de revisión de @nicsanmen

**Comment by nicsanmen** [comment]
he estado revisando y voy a añadir algunas cosas a modificar en el propio overleaf
